name: TradeSystemPlugin
main: com.gmail.risterral.TradeSystemPlugin
version: 1.3.1

commands:
  trade:
    description: Trades with targeted player.
    usage: "'/trade' while targeting another player, to start trading."
    permission: TradeSystemPlugin.ableToTrade
    permission-message: You don't have permission to trade.
  accept:
    description: Accept any trades from other players.
    usage: "'accept trades' to accept all possible trades."
    permission: TradeSystemPlugin.ableToTrade
    permission-message: You don't have permission to trade.
  reject:
    description: Reject any trades from other players.
    usage: "'reject trades' to reject all possible trades (beside OPed players trades)."
    permission: TradeSystemPlugin.ableToTrade
    permission-message: You don't have permission to trade.